# Global
project: lostpet
data: data25
seed: 2022
output_dir: /data/hse/model/     # Modify according to your path

# DataModual
train_csv: /data/hse/data_crop_body/train.csv  # Modify according to original data path
test_csv: /data/hse/data_crop_body/val.csv     # Modify according to original data path
image_size: 224
batch_size: 32
num_workers: 4  # larger need big RAM

# Model
model_type: LitModule
model_name: convnext_small
pretrained: true
drop_rate: 0.0
embedding_size: 512
num_classes: 46400
arc_s: 30.0
arc_m: 0.5
arc_easy_margin: false
arc_ls_eps: 0.0
optimizer: adam
learning_rate: 3.0e-4
weight_decay: 1.0e-6
bnneck: false
arcface: true

# Train parameters
accumulate_grad_batches: 1
auto_lr_find: false
auto_scale_batch_size: false
fast_dev_run: false
max_epochs: 10
precision: 16
stochastic_weight_avg: true
